<?php

namespace App\Providers;

use Carbon\CarbonImmutable;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Routing\Events\RouteMatched;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Rules\Password;
use RuntimeException;
use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->configureDefaults();
        $this->configureRateLimiting();
        $this->throttlePasswordResetRoutes();
    }

    /**
     * Configure default behaviors for production-ready applications.
     */
    protected function configureDefaults(): void
    {
        Date::use(CarbonImmutable::class);

        DB::prohibitDestructiveCommands(
            app()->isProduction(),
        );

        Password::defaults(fn (): ?Password => app()->isProduction()
            ? Password::min(12)
                ->mixedCase()
                ->letters()
                ->numbers()
                ->symbols()
                ->uncompromised()
            : null,
        );

        if (app()->isProduction()) {
            // Enrollment tokens, the long-lived node credential, and the session cookie all
            // depend on every request really being HTTPS (see AuthenticateNodeCredential and
            // config/session.php's own "secure" flag) -- forcing the scheme here means a stray
            // absolute http:// link, redirect, or asset URL can never be generated by the app
            // itself, on top of TrustProxies (bootstrap/app.php) correctly resolving the real
            // client scheme behind nginx.
            URL::forceScheme('https');

            // A misconfigured production deploy that skips install-cp.sh (which forces this
            // itself) must fail loudly, not silently leak stack traces, file paths, and SQL in
            // error responses to every visitor.
            if (config('app.debug')) {
                throw new RuntimeException('APP_DEBUG must be false when APP_ENV=production.');
            }
        }
    }

    /**
     * Configure rate limiting for the agent-facing routes (routes/agent.php).
     */
    protected function configureRateLimiting(): void
    {
        RateLimiter::for('agent', function (Request $request) {
            return Limit::perMinute(120)->by($request->bearerToken() ?? $request->ip());
        });

        RateLimiter::for('agent-enroll', function (Request $request) {
            return Limit::perMinute(5)->by($request->ip());
        });

        RateLimiter::for('reset-password', function (Request $request) {
            return Limit::perMinute(3)->by($request->ip());
        });
    }

    /**
     * Fortify's own password.email/password.update routes (vendor/laravel/fortify/routes/
     * routes.php) have no rate-limiting hook at all -- unlike login/two-factor/passkeys, which
     * each read a named limiter from config('fortify.limiters.*'), Fortify never exposes an
     * equivalent config key for password reset. Both routes are unlimited requests otherwise:
     * unbounded "forgot password" submissions enable email-flooding a target address, and
     * unbounded reset-token submissions remove the last friction against a leaked/guessed token.
     *
     * Enforced on the RouteMatched event, not by attaching the "throttle:reset-password"
     * middleware to the already-registered routes by name: confirmed directly (not assumed) that
     * this app's routing bootstrap only finishes loading route files (including Fortify's own,
     * package-discovered separately from this app's own FortifyServiceProvider) AFTER
     * Application::booted() callbacks already fired, so a route mutation deferred to
     * app()->booted() silently never finds the route and never attaches anything. RouteMatched
     * fires per-request, strictly after routing has resolved a real match, sidestepping that
     * ordering question entirely. Reuses the "reset-password" limiter registered above as the
     * single source of truth for the actual limit.
     */
    protected function throttlePasswordResetRoutes(): void
    {
        Route::matched(function (RouteMatched $event): void {
            if (! in_array($event->route->getName(), ['password.email', 'password.update'], true)) {
                return;
            }

            $limit = RateLimiter::limiter('reset-password')($event->request);

            if (RateLimiter::tooManyAttempts($limit->key, $limit->maxAttempts)) {
                throw new TooManyRequestsHttpException(RateLimiter::availableIn($limit->key));
            }

            RateLimiter::hit($limit->key, $limit->decaySeconds);
        });
    }
}
